name: CI
on: [push]

jobs:
  build:
    name: release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get current package version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.1.0
    - name: Create a Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name : ${{ steps.package-version.outputs.current-version}}
        release_name: ${{ steps.package-version.outputs.current-version}}
        body: Publish ${{ steps.package-version.outputs.current-version}}

