name: CI
on: [push]

jobs:
  build:
    name: release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    # Run install dependencies
    - name: Install dependencies
      run: npm install
    # Run tests
    - name: Build 
      run: npm run compile
    - name: Create vsix
      id: create-vsix
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: 'fake'
        dryRun: true
    - name: use output
      run: |
        echo $json_var
      env:
        json_var: ${{ steps.create-vsix.outputs.vsixPath}}
    

